apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/danielfarias82/mmj_poc"
    targetRevision: HEAD
    path: temporal
    helm:
      valueFiles:
        - values.postgresql.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
