apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-server
  labels:
    app: temporal
spec:
  replicas: {{ .Values.server.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal-server
          image: temporalio/server:{{ .Chart.AppVersion }}
          ports:
            - containerPort: 7233
          envFrom:
            - configMapRef:
                name: temporal-config
