apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/danielfarias82/mmj_poc.git"
    targetRevision: HEAD
    path: temporal
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
